server:
  http_listen_port: 3200
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
