server:
  listen: ":9001"
log:
  level: warn
nats:
  url: "nats://nats:4222"
clickhouse:
  addr: "clickhouse:9000"
  database: "alfq"
  username: "alfq"
  password_env: CLICKHOUSE_PASSWORD
accounts: []
