-- 003: MT account binding
-- Add MT connection fields to accounts table

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS status       TEXT NOT NULL DEFAULT 'disconnected';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS balance      DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS equity       DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS margin       DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS free_margin  DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS margin_level DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS profit       DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS profit_percent DOUBLE PRECISION DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS is_disabled  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_error   TEXT DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS alias        TEXT DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS connected_at TIMESTAMPTZ;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_at   TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS updated_at   TIMESTAMPTZ NOT NULL DEFAULT now();
